// Generated by tools/compile-assets.mjs. Do not edit by hand.

export const GENERATED_RESOURCE_ART = {
  "bound-lumber": {
    "surfaceUrl": "/assets/runtime/materials/resources/board/bound-lumber.png",
    "colorways": [
      {
        "id": "brown",
        "label": "Brown",
        "sourceUrl": "/assets/runtime/materials/resources/board/bound-lumber.brown.png"
      },
      {
        "id": "green",
        "label": "Green",
        "sourceUrl": "/assets/runtime/materials/resources/board/bound-lumber.green.png"
      },
      {
        "id": "purple",
        "label": "Purple",
        "sourceUrl": "/assets/runtime/materials/resources/board/bound-lumber.purple.png"
      },
      {
        "id": "blue",
        "label": "Blue",
        "sourceUrl": "/assets/runtime/materials/resources/board/bound-lumber.blue.png"
      },
      {
        "id": "teal",
        "label": "Teal",
        "sourceUrl": "/assets/runtime/materials/resources/board/bound-lumber.teal.png"
      },
      {
        "id": "pink",
        "label": "Pink",
        "sourceUrl": "/assets/runtime/materials/resources/board/bound-lumber.pink.png"
      }
    ],
    "looseTemplate": "board",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/bound-lumber/loose-01.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/bound-lumber/loose-02.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/bound-lumber/loose-03.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/bound-lumber/loose-04.png",
        "aspectRatio": 2
      }
    ]
  },
  "crossbound-timber": {
    "surfaceUrl": "/assets/runtime/materials/resources/board/crossbound-timber.png",
    "colorways": [
      {
        "id": "brown",
        "label": "Brown",
        "sourceUrl": "/assets/runtime/materials/resources/board/crossbound-timber.brown.png"
      },
      {
        "id": "grey",
        "label": "Grey",
        "sourceUrl": "/assets/runtime/materials/resources/board/crossbound-timber.grey.png"
      },
      {
        "id": "red",
        "label": "Red",
        "sourceUrl": "/assets/runtime/materials/resources/board/crossbound-timber.red.png"
      },
      {
        "id": "blue",
        "label": "Blue",
        "sourceUrl": "/assets/runtime/materials/resources/board/crossbound-timber.blue.png"
      },
      {
        "id": "cream",
        "label": "Cream",
        "sourceUrl": "/assets/runtime/materials/resources/board/crossbound-timber.cream.png"
      }
    ],
    "looseTemplate": "board",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/crossbound-timber/loose-01.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/crossbound-timber/loose-02.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/crossbound-timber/loose-03.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/crossbound-timber/loose-04.png",
        "aspectRatio": 2
      }
    ]
  },
  "graphite-cardstock": {
    "surfaceUrl": "/assets/runtime/materials/resources/board/graphite-cardstock.png",
    "colorways": [],
    "looseTemplate": "board",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/graphite-cardstock/loose-01.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/graphite-cardstock/loose-02.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/graphite-cardstock/loose-03.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/graphite-cardstock/loose-04.png",
        "aspectRatio": 2
      }
    ]
  },
  "layerboard": {
    "surfaceUrl": "/assets/runtime/materials/resources/board/layerboard.png",
    "colorways": [
      {
        "id": "purple",
        "label": "Purple",
        "sourceUrl": "/assets/runtime/materials/resources/board/layerboard.purple.png"
      },
      {
        "id": "blue",
        "label": "Blue",
        "sourceUrl": "/assets/runtime/materials/resources/board/layerboard.blue.png"
      },
      {
        "id": "teal",
        "label": "Teal",
        "sourceUrl": "/assets/runtime/materials/resources/board/layerboard.teal.png"
      },
      {
        "id": "pink",
        "label": "Pink",
        "sourceUrl": "/assets/runtime/materials/resources/board/layerboard.pink.png"
      },
      {
        "id": "yellow",
        "label": "Yellow",
        "sourceUrl": "/assets/runtime/materials/resources/board/layerboard.yellow.png"
      },
      {
        "id": "red",
        "label": "Red",
        "sourceUrl": "/assets/runtime/materials/resources/board/layerboard.red.png"
      },
      {
        "id": "green",
        "label": "Green",
        "sourceUrl": "/assets/runtime/materials/resources/board/layerboard.green.png"
      }
    ],
    "looseTemplate": "board",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/layerboard/loose-01.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/layerboard/loose-02.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/layerboard/loose-03.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/layerboard/loose-04.png",
        "aspectRatio": 2
      }
    ]
  },
  "storybeam": {
    "surfaceUrl": "/assets/runtime/materials/resources/board/storybeam.png",
    "colorways": [
      {
        "id": "pink",
        "label": "Pink",
        "sourceUrl": "/assets/runtime/materials/resources/board/storybeam.pink.png"
      },
      {
        "id": "green",
        "label": "Green",
        "sourceUrl": "/assets/runtime/materials/resources/board/storybeam.green.png"
      },
      {
        "id": "blue",
        "label": "Blue",
        "sourceUrl": "/assets/runtime/materials/resources/board/storybeam.blue.png"
      },
      {
        "id": "purple",
        "label": "Purple",
        "sourceUrl": "/assets/runtime/materials/resources/board/storybeam.purple.png"
      },
      {
        "id": "orange",
        "label": "Orange",
        "sourceUrl": "/assets/runtime/materials/resources/board/storybeam.orange.png"
      },
      {
        "id": "darkblue",
        "label": "Darkblue",
        "sourceUrl": "/assets/runtime/materials/resources/board/storybeam.darkblue.png"
      },
      {
        "id": "yellow",
        "label": "Yellow",
        "sourceUrl": "/assets/runtime/materials/resources/board/storybeam.yellow.png"
      },
      {
        "id": "greyish",
        "label": "Greyish",
        "sourceUrl": "/assets/runtime/materials/resources/board/storybeam.greyish.png"
      },
      {
        "id": "black",
        "label": "Black",
        "sourceUrl": "/assets/runtime/materials/resources/board/storybeam.black.png"
      }
    ],
    "looseTemplate": "board",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/storybeam/loose-01.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/storybeam/loose-02.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/storybeam/loose-03.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/storybeam/loose-04.png",
        "aspectRatio": 2
      }
    ]
  },
  "cream-city-brick": {
    "surfaceUrl": "/assets/runtime/materials/resources/brick/cream-city-brick.png",
    "colorways": [],
    "looseTemplate": "brick",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/cream-city-brick/loose-01.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/cream-city-brick/loose-02.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/cream-city-brick/loose-03.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/cream-city-brick/loose-04.png",
        "aspectRatio": 1.5
      }
    ]
  },
  "grey-brick": {
    "surfaceUrl": "/assets/runtime/materials/resources/brick/grey-brick.png",
    "colorways": [],
    "looseTemplate": "brick",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/grey-brick/loose-01.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/grey-brick/loose-02.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/grey-brick/loose-03.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/grey-brick/loose-04.png",
        "aspectRatio": 1.5
      }
    ]
  },
  "red-brick": {
    "surfaceUrl": "/assets/runtime/materials/resources/brick/red-brick.png",
    "colorways": [],
    "looseTemplate": "brick",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/red-brick/loose-01.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/red-brick/loose-02.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/red-brick/loose-03.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/red-brick/loose-04.png",
        "aspectRatio": 1.5
      }
    ]
  },
  "agave-fiber": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/agave-fiber.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/agave-fiber/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/agave-fiber/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/agave-fiber/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/agave-fiber/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/agave-fiber/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/agave-fiber/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "allium-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/allium-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/allium-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/allium-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/allium-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/allium-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/allium-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/allium-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "alpine-resin-paper": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/alpine-resin-paper.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/alpine-resin-paper/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/alpine-resin-paper/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/alpine-resin-paper/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/alpine-resin-paper/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/alpine-resin-paper/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/alpine-resin-paper/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "anthurium-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/anthurium-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/anthurium-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/anthurium-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/anthurium-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/anthurium-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/anthurium-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/anthurium-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "baobab-pith-fiber": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/baobab-pith-fiber.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/baobab-pith-fiber/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/baobab-pith-fiber/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/baobab-pith-fiber/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/baobab-pith-fiber/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/baobab-pith-fiber/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/baobab-pith-fiber/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "bird-of-paradise-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/bird-of-paradise-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/bird-of-paradise-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/bird-of-paradise-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/bird-of-paradise-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/bird-of-paradise-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/bird-of-paradise-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/bird-of-paradise-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "blackeyed-susan-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/blackeyed-susan-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/blackeyed-susan-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/blackeyed-susan-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/blackeyed-susan-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/blackeyed-susan-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/blackeyed-susan-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/blackeyed-susan-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "blotting-caps": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/blotting-caps.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/blotting-caps/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/blotting-caps/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/blotting-caps/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/blotting-caps/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/blotting-caps/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/blotting-caps/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "bougainvillea-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/bougainvillea-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/bougainvillea-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/bougainvillea-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/bougainvillea-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/bougainvillea-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/bougainvillea-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/bougainvillea-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "cactus-fiber": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/cactus-fiber.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/cactus-fiber/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cactus-fiber/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cactus-fiber/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cactus-fiber/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cactus-fiber/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cactus-fiber/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "cattail": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/cattail.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/cattail/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cattail/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cattail/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cattail/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cattail/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cattail/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "coneflower-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/coneflower-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/coneflower-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/coneflower-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/coneflower-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/coneflower-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/coneflower-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/coneflower-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "cosmos-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/cosmos-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/cosmos-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cosmos-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cosmos-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cosmos-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cosmos-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cosmos-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "crepe-vine": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/crepe-vine.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/crepe-vine/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/crepe-vine/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/crepe-vine/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/crepe-vine/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/crepe-vine/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/crepe-vine/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "daisy-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/daisy-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/daisy-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/daisy-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/daisy-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/daisy-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/daisy-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/daisy-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "edelweiss-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/edelweiss-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/edelweiss-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/edelweiss-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/edelweiss-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/edelweiss-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/edelweiss-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/edelweiss-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "foxglove-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/foxglove-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/foxglove-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/foxglove-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/foxglove-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/foxglove-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/foxglove-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/foxglove-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "hibiscus-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/hibiscus-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/hibiscus-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/hibiscus-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/hibiscus-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/hibiscus-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/hibiscus-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/hibiscus-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "lotus-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/lotus-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/lotus-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/lotus-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/lotus-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/lotus-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/lotus-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/lotus-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "lupine-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/lupine-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/lupine-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/lupine-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/lupine-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/lupine-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/lupine-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/lupine-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "marigold-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/marigold-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/marigold-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marigold-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marigold-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marigold-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marigold-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marigold-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "marsh-grass": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/marsh-grass.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/marsh-grass/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marsh-grass/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marsh-grass/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marsh-grass/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marsh-grass/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marsh-grass/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "mossy-paper-fiber": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/mossy-paper-fiber.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/mossy-paper-fiber/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/mossy-paper-fiber/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/mossy-paper-fiber/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/mossy-paper-fiber/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/mossy-paper-fiber/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/mossy-paper-fiber/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "paintbrush-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/paintbrush-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/paintbrush-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/paintbrush-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/paintbrush-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/paintbrush-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/paintbrush-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/paintbrush-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "palm-fiber": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/palm-fiber.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/palm-fiber/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/palm-fiber/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/palm-fiber/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/palm-fiber/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/palm-fiber/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/palm-fiber/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "plumeria-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/plumeria-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/plumeria-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/plumeria-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/plumeria-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/plumeria-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/plumeria-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/plumeria-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "poppy-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/poppy-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/poppy-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/poppy-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/poppy-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/poppy-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/poppy-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/poppy-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "pressed-petal-confetti": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/pressed-petal-confetti.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/pressed-petal-confetti/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/pressed-petal-confetti/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/pressed-petal-confetti/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/pressed-petal-confetti/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/pressed-petal-confetti/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/pressed-petal-confetti/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "protea-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/protea-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/protea-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/protea-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/protea-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/protea-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/protea-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/protea-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "shrub": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/shrub.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/shrub/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/shrub/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/shrub/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/shrub/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/shrub/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/shrub/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "spider-lily-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/spider-lily-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/spider-lily-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/spider-lily-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/spider-lily-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/spider-lily-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/spider-lily-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/spider-lily-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "sunflower-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/sunflower-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/sunflower-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/sunflower-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/sunflower-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/sunflower-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/sunflower-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/sunflower-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "zinnia-petals": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/zinnia-petals.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/zinnia-petals/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/zinnia-petals/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/zinnia-petals/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/zinnia-petals/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/zinnia-petals/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/zinnia-petals/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "jungle-loam": {
    "surfaceUrl": "/assets/runtime/materials/resources/soil/jungle-loam.png",
    "colorways": [],
    "looseTemplate": "soil",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/jungle-loam/loose-01.png",
        "aspectRatio": 1.3571428571428572
      },
      {
        "sourceUrl": "/assets/runtime/resources/jungle-loam/loose-02.png",
        "aspectRatio": 1.3571428571428572
      },
      {
        "sourceUrl": "/assets/runtime/resources/jungle-loam/loose-03.png",
        "aspectRatio": 1.3571428571428572
      },
      {
        "sourceUrl": "/assets/runtime/resources/jungle-loam/loose-04.png",
        "aspectRatio": 1.3571428571428572
      }
    ]
  },
  "ochre-paperclay": {
    "surfaceUrl": "/assets/runtime/materials/resources/soil/ochre-paperclay.png",
    "colorways": [],
    "looseTemplate": "soil",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/ochre-paperclay/loose-01.png",
        "aspectRatio": 1.3571428571428572
      },
      {
        "sourceUrl": "/assets/runtime/resources/ochre-paperclay/loose-02.png",
        "aspectRatio": 1.3571428571428572
      },
      {
        "sourceUrl": "/assets/runtime/resources/ochre-paperclay/loose-03.png",
        "aspectRatio": 1.3571428571428572
      },
      {
        "sourceUrl": "/assets/runtime/resources/ochre-paperclay/loose-04.png",
        "aspectRatio": 1.3571428571428572
      }
    ]
  },
  "basalt": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/basalt.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/basalt/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/basalt/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/basalt/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/basalt/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/basalt/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/basalt/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "bluefold-pebbles": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/bluefold-pebbles.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/bluefold-pebbles/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/bluefold-pebbles/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/bluefold-pebbles/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/bluefold-pebbles/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/bluefold-pebbles/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/bluefold-pebbles/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "carbon-copy-shale": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/carbon-copy-shale.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/carbon-copy-shale/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/carbon-copy-shale/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/carbon-copy-shale/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/carbon-copy-shale/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/carbon-copy-shale/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/carbon-copy-shale/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "confetti-stones": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/confetti-stones.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/confetti-stones/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/confetti-stones/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/confetti-stones/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/confetti-stones/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/confetti-stones/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/confetti-stones/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "foil": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/foil.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/foil/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/foil/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/foil/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/foil/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/foil/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/foil/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "graphite-cardstone": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/graphite-cardstone.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/graphite-cardstone/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/graphite-cardstone/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/graphite-cardstone/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/graphite-cardstone/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/graphite-cardstone/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/graphite-cardstone/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "iron-rock": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/iron-rock.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/iron-rock/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/iron-rock/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/iron-rock/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/iron-rock/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/iron-rock/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/iron-rock/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "marblewrap": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/marblewrap.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/marblewrap/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/marblewrap/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/marblewrap/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/marblewrap/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/marblewrap/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/marblewrap/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "quartz": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/quartz.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/quartz/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/quartz/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/quartz/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/quartz/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/quartz/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/quartz/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "rainfold-pebbles": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/rainfold-pebbles.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/rainfold-pebbles/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/rainfold-pebbles/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/rainfold-pebbles/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/rainfold-pebbles/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/rainfold-pebbles/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/rainfold-pebbles/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "sandstone": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/sandstone.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/sandstone/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/sandstone/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/sandstone/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/sandstone/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/sandstone/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/sandstone/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "slate": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/slate.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/slate/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/slate/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/slate/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/slate/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/slate/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/slate/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "terracotta-pebbles": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/terracotta-pebbles.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/terracotta-pebbles/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/terracotta-pebbles/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/terracotta-pebbles/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/terracotta-pebbles/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/terracotta-pebbles/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/terracotta-pebbles/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "acacia-thornwood": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/acacia-thornwood.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/acacia-thornwood/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/acacia-thornwood/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/acacia-thornwood/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/acacia-thornwood/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/acacia-thornwood/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/acacia-thornwood/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "bamboo-strips": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/bamboo-strips.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/bamboo-strips/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/bamboo-strips/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/bamboo-strips/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/bamboo-strips/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/bamboo-strips/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/bamboo-strips/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "banana-leaf-clippings": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/banana-leaf-clippings.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/banana-leaf-clippings/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/banana-leaf-clippings/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/banana-leaf-clippings/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/banana-leaf-clippings/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/banana-leaf-clippings/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/banana-leaf-clippings/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "barrel-cactus-clippings": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/barrel-cactus-clippings.png",
    "colorways": [
      {
        "id": "green",
        "label": "Green",
        "sourceUrl": "/assets/runtime/materials/resources/wood/barrel-cactus-clippings.green.png"
      },
      {
        "id": "blue",
        "label": "Blue",
        "sourceUrl": "/assets/runtime/materials/resources/wood/barrel-cactus-clippings.blue.png"
      },
      {
        "id": "red",
        "label": "Red",
        "sourceUrl": "/assets/runtime/materials/resources/wood/barrel-cactus-clippings.red.png"
      },
      {
        "id": "purple",
        "label": "Purple",
        "sourceUrl": "/assets/runtime/materials/resources/wood/barrel-cactus-clippings.purple.png"
      },
      {
        "id": "teal",
        "label": "Teal",
        "sourceUrl": "/assets/runtime/materials/resources/wood/barrel-cactus-clippings.teal.png"
      },
      {
        "id": "yellow",
        "label": "Yellow",
        "sourceUrl": "/assets/runtime/materials/resources/wood/barrel-cactus-clippings.yellow.png"
      },
      {
        "id": "darkblue",
        "label": "Darkblue",
        "sourceUrl": "/assets/runtime/materials/resources/wood/barrel-cactus-clippings.darkblue.png"
      },
      {
        "id": "orange",
        "label": "Orange",
        "sourceUrl": "/assets/runtime/materials/resources/wood/barrel-cactus-clippings.orange.png"
      },
      {
        "id": "pink",
        "label": "Pink",
        "sourceUrl": "/assets/runtime/materials/resources/wood/barrel-cactus-clippings.pink.png"
      }
    ],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/barrel-cactus-clippings/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/barrel-cactus-clippings/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/barrel-cactus-clippings/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/barrel-cactus-clippings/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/barrel-cactus-clippings/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/barrel-cactus-clippings/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "column-cactus-clippings": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/column-cactus-clippings.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/column-cactus-clippings/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/column-cactus-clippings/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/column-cactus-clippings/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/column-cactus-clippings/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/column-cactus-clippings/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/column-cactus-clippings/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "cypress-bark-folds": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/cypress-bark-folds.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/cypress-bark-folds/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/cypress-bark-folds/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/cypress-bark-folds/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/cypress-bark-folds/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/cypress-bark-folds/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/cypress-bark-folds/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "kraft-twigs": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/kraft-twigs.png",
    "colorways": [
      {
        "id": "terracotta",
        "label": "Terracotta",
        "sourceUrl": "/assets/runtime/materials/resources/wood/kraft-twigs.terracotta.png"
      },
      {
        "id": "kraft",
        "label": "Kraft",
        "sourceUrl": "/assets/runtime/materials/resources/wood/kraft-twigs.kraft.png"
      },
      {
        "id": "moss",
        "label": "Moss",
        "sourceUrl": "/assets/runtime/materials/resources/wood/kraft-twigs.moss.png"
      },
      {
        "id": "browns",
        "label": "Brown",
        "sourceUrl": "/assets/runtime/materials/resources/wood/kraft-twigs.browns.png"
      },
      {
        "id": "maroon",
        "label": "Maroon",
        "sourceUrl": "/assets/runtime/materials/resources/wood/kraft-twigs.maroon.png"
      },
      {
        "id": "mint",
        "label": "Mint",
        "sourceUrl": "/assets/runtime/materials/resources/wood/kraft-twigs.mint.png"
      }
    ],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/kraft-twigs/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/kraft-twigs/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/kraft-twigs/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/kraft-twigs/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/kraft-twigs/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/kraft-twigs/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "leafy-clippings": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/leafy-clippings.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/leafy-clippings/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-clippings/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-clippings/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-clippings/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-clippings/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-clippings/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "leafy-tree": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/leafy-tree.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/leafy-tree/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-tree/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-tree/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-tree/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-tree/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-tree/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "paddle-cactus-clippings": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/paddle-cactus-clippings.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/paddle-cactus-clippings/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/paddle-cactus-clippings/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/paddle-cactus-clippings/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/paddle-cactus-clippings/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/paddle-cactus-clippings/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/paddle-cactus-clippings/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "palm-clippings": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/palm-clippings.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/palm-clippings/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/palm-clippings/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/palm-clippings/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/palm-clippings/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/palm-clippings/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/palm-clippings/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "redwood-bark-curls": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/redwood-bark-curls.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/redwood-bark-curls/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/redwood-bark-curls/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/redwood-bark-curls/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/redwood-bark-curls/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/redwood-bark-curls/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/redwood-bark-curls/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "ribbonwood-sticks": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/ribbonwood-sticks.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/ribbonwood-sticks/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/ribbonwood-sticks/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/ribbonwood-sticks/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/ribbonwood-sticks/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/ribbonwood-sticks/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/ribbonwood-sticks/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "supple-shrub-shoots": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/supple-shrub-shoots.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/supple-shrub-shoots/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/supple-shrub-shoots/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/supple-shrub-shoots/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/supple-shrub-shoots/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/supple-shrub-shoots/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/supple-shrub-shoots/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  }
} as const;
