// Generated by tools/compile-assets.mjs. Do not edit by hand.

export const GENERATED_RESOURCE_ART = {
  "layerboard": {
    "surfaceUrl": "/assets/runtime/materials/resources/board/layerboard.png",
    "colorways": [],
    "looseTemplate": "board",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/layerboard/loose-01.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/layerboard/loose-02.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/layerboard/loose-03.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/layerboard/loose-04.png",
        "aspectRatio": 2
      }
    ]
  },
  "storybeam": {
    "surfaceUrl": "/assets/runtime/materials/resources/board/storybeam.png",
    "colorways": [],
    "looseTemplate": "board",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/storybeam/loose-01.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/storybeam/loose-02.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/storybeam/loose-03.png",
        "aspectRatio": 2
      },
      {
        "sourceUrl": "/assets/runtime/resources/storybeam/loose-04.png",
        "aspectRatio": 2
      }
    ]
  },
  "cream-city-brick": {
    "surfaceUrl": "/assets/runtime/materials/resources/brick/cream-city-brick.png",
    "colorways": [],
    "looseTemplate": "brick",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/cream-city-brick/loose-01.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/cream-city-brick/loose-02.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/cream-city-brick/loose-03.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/cream-city-brick/loose-04.png",
        "aspectRatio": 1.5
      }
    ]
  },
  "grey-brick": {
    "surfaceUrl": "/assets/runtime/materials/resources/brick/grey-brick.png",
    "colorways": [],
    "looseTemplate": "brick",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/grey-brick/loose-01.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/grey-brick/loose-02.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/grey-brick/loose-03.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/grey-brick/loose-04.png",
        "aspectRatio": 1.5
      }
    ]
  },
  "red-brick": {
    "surfaceUrl": "/assets/runtime/materials/resources/brick/red-brick.png",
    "colorways": [],
    "looseTemplate": "brick",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/red-brick/loose-01.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/red-brick/loose-02.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/red-brick/loose-03.png",
        "aspectRatio": 1.5
      },
      {
        "sourceUrl": "/assets/runtime/resources/red-brick/loose-04.png",
        "aspectRatio": 1.5
      }
    ]
  },
  "cattail": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/cattail.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/cattail/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cattail/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cattail/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cattail/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cattail/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/cattail/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "marsh-grass": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/marsh-grass.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/marsh-grass/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marsh-grass/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marsh-grass/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marsh-grass/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marsh-grass/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/marsh-grass/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "shrub": {
    "surfaceUrl": "/assets/runtime/materials/resources/fiber/shrub.png",
    "colorways": [],
    "looseTemplate": "fiber",
    "orientation": "standing",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/shrub/loose-01.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/shrub/loose-02.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/shrub/loose-03.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/shrub/loose-04.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/shrub/loose-05.png",
        "aspectRatio": 0.5818181818181818
      },
      {
        "sourceUrl": "/assets/runtime/resources/shrub/loose-06.png",
        "aspectRatio": 0.5818181818181818
      }
    ]
  },
  "ochre-paperclay": {
    "surfaceUrl": "/assets/runtime/materials/resources/soil/ochre-paperclay.png",
    "colorways": [],
    "looseTemplate": "soil",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/ochre-paperclay/loose-01.png",
        "aspectRatio": 1.3571428571428572
      },
      {
        "sourceUrl": "/assets/runtime/resources/ochre-paperclay/loose-02.png",
        "aspectRatio": 1.3571428571428572
      },
      {
        "sourceUrl": "/assets/runtime/resources/ochre-paperclay/loose-03.png",
        "aspectRatio": 1.3571428571428572
      },
      {
        "sourceUrl": "/assets/runtime/resources/ochre-paperclay/loose-04.png",
        "aspectRatio": 1.3571428571428572
      }
    ]
  },
  "basalt": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/basalt.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/basalt/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/basalt/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/basalt/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/basalt/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/basalt/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/basalt/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "bluefold-pebbles": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/bluefold-pebbles.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/bluefold-pebbles/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/bluefold-pebbles/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/bluefold-pebbles/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/bluefold-pebbles/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/bluefold-pebbles/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/bluefold-pebbles/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "confetti-stones": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/confetti-stones.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/confetti-stones/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/confetti-stones/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/confetti-stones/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/confetti-stones/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/confetti-stones/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/confetti-stones/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "foil": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/foil.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/foil/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/foil/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/foil/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/foil/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/foil/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/foil/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "iron-rock": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/iron-rock.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/iron-rock/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/iron-rock/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/iron-rock/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/iron-rock/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/iron-rock/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/iron-rock/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "marblewrap": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/marblewrap.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/marblewrap/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/marblewrap/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/marblewrap/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/marblewrap/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/marblewrap/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/marblewrap/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "quartz": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/quartz.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/quartz/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/quartz/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/quartz/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/quartz/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/quartz/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/quartz/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "sandstone": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/sandstone.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/sandstone/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/sandstone/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/sandstone/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/sandstone/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/sandstone/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/sandstone/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "slate": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/slate.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/slate/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/slate/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/slate/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/slate/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/slate/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/slate/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "terracotta-pebbles": {
    "surfaceUrl": "/assets/runtime/materials/resources/stone/terracotta-pebbles.png",
    "colorways": [],
    "looseTemplate": "stone",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/terracotta-pebbles/loose-01.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/terracotta-pebbles/loose-02.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/terracotta-pebbles/loose-03.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/terracotta-pebbles/loose-04.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/terracotta-pebbles/loose-05.png",
        "aspectRatio": 1.2
      },
      {
        "sourceUrl": "/assets/runtime/resources/terracotta-pebbles/loose-06.png",
        "aspectRatio": 1.2
      }
    ]
  },
  "barrel-cactus": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/barrel-cactus.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/barrel-cactus/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/barrel-cactus/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/barrel-cactus/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/barrel-cactus/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/barrel-cactus/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/barrel-cactus/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "column-cactus": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/column-cactus.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/column-cactus/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/column-cactus/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/column-cactus/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/column-cactus/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/column-cactus/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/column-cactus/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "crossbound-timber": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/crossbound-timber.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/crossbound-timber/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/crossbound-timber/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/crossbound-timber/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/crossbound-timber/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/crossbound-timber/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/crossbound-timber/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "leafy-tree": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/leafy-tree.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/leafy-tree/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-tree/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-tree/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-tree/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-tree/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/leafy-tree/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "paddle-cactus": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/paddle-cactus.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/paddle-cactus/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/paddle-cactus/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/paddle-cactus/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/paddle-cactus/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/paddle-cactus/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/paddle-cactus/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "redwood-bark-curls": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/redwood-bark-curls.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/redwood-bark-curls/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/redwood-bark-curls/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/redwood-bark-curls/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/redwood-bark-curls/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/redwood-bark-curls/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/redwood-bark-curls/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  },
  "ribbonwood-sticks": {
    "surfaceUrl": "/assets/runtime/materials/resources/wood/ribbonwood-sticks.png",
    "colorways": [],
    "looseTemplate": "wood",
    "orientation": "flat",
    "variants": [
      {
        "sourceUrl": "/assets/runtime/resources/ribbonwood-sticks/loose-01.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/ribbonwood-sticks/loose-02.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/ribbonwood-sticks/loose-03.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/ribbonwood-sticks/loose-04.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/ribbonwood-sticks/loose-05.png",
        "aspectRatio": 2.6666666666666665
      },
      {
        "sourceUrl": "/assets/runtime/resources/ribbonwood-sticks/loose-06.png",
        "aspectRatio": 2.6666666666666665
      }
    ]
  }
} as const;
