import type { QuestDef } from './quests';

/**
 * Additional quest content, kept in its own file so the authored set in
 * `quests.ts` stays readable and so new quests can be added without touching
 * the runtime. `allQuestDefs()` merges the two by id.
 *
 * Only real catalog ids (resources, seeds, tools, recipes, biomes, build
 * pieces, critter ids) may appear here. `tools/validate-quests.mjs` checks it.
 *
 * The three tiers follow `quests.ts`'s own ladder — `favor` is a single warm
 * step at `curious`, `errand` is two steps at `friend`, and `odyssey` is a
 * multi-step job at `buddy`/`pet` that usually carries something (a message,
 * a living plant, a length of lumber) between places or climbs one rung of a
 * tool/plan ladder. Nothing here may be out of reach: every id is one the
 * player can actually obtain, so `questReachable` can honestly keep offering.
 */
export const QUEST_EXPANSION_DEFS: QuestDef[] = [
  // --- Favor: a single, small, warm step ------------------------------------
  {
    id: 'favor-meadow-fiber',
    title: 'Soft Stuffing',
    summary: 'Gather mossy paper fiber for a nest lining.',
    tier: 'favor',
    giverSpecies: ['bunny', 'bird', 'butterfly', 'squirrel'],
    minFriendship: 'curious',
    objectives: [{ kind: 'collect', resource: 'mossy-paper-fiber', quantity: 3 }],
    reward: { trinketFamily: 'natural', trinketTag: 'plant', friendship: 6 },
    opening: [
      '“The nest is lumpy in a way I have decided to care about,” {{name}} sighs. “Three tufts of mossy fiber and it would be a palace.”',
    ],
    acceptLabel: 'I’ll gather some',
    acceptReply: ['“It grows in the soft green places. You will feel it before you see it.”'],
    declineLabel: 'Another time',
    declineReply: ['“The lump will keep. It always does.”'],
    progressOpening: ['“Any fiber yet? The lump is still there. Judging me.”'],
    turnInOpening: ['“Oh, that is lovely and soft.” {{name}} tucks it in. “Here — I found this and it made me think of you.”'],
    turnInReply: ['{{name}} presses a small treasure into your palm.'],
  },
  {
    id: 'favor-bluefold-pond',
    title: 'Pebbles by the Pond',
    summary: 'Collect bluefold pebbles from the meadow.',
    tier: 'favor',
    giverSpecies: ['raccoon', 'cat', 'bird'],
    minFriendship: 'curious',
    objectives: [{ kind: 'collect', resource: 'bluefold-pebbles', quantity: 2 }],
    reward: { trinketFamily: 'natural', trinketTag: 'material:stone', friendship: 6 },
    opening: [
      '“Bluefold pebbles,” {{name}} says dreamily. “They only lie about in the meadow. Two of them and I will consider my day complete.”',
    ],
    acceptLabel: 'I’ll look',
    acceptReply: ['“Soft blue, folded over like a letter. You cannot miss them once you notice them.”'],
    declineLabel: 'Not now',
    declineReply: ['“They are very good at waiting, pebbles.”'],
    progressOpening: ['“Bluefolds? They look like tiny folded letters.”'],
    turnInOpening: ['“Yes, exactly these.” {{name}} rolls them between their paws. “Take this in trade. It is shinier than a pebble, I promise.”'],
    turnInReply: ['{{name}} hands over a shiny little thing.'],
  },
  {
    id: 'favor-dark-earth',
    title: 'Pocketful of Dusk',
    summary: 'Bring a little carbon soil back from under the trees.',
    tier: 'favor',
    giverSpecies: ['woodchuck', 'raccoon', 'bunny'],
    giverPersonalities: ['curious', 'gentle'],
    minFriendship: 'curious',
    objectives: [{ kind: 'collect', resource: 'carbon-soil', quantity: 2 }],
    reward: { trinketFamily: 'natural', trinketTag: 'biome:forest', friendship: 6 },
    opening: [
      '“You have the look of someone who has not dug in the woods yet,” {{name}} says. “Two scoops of the dark soil under the pines and I will call you a proper forager.”',
    ],
    acceptLabel: 'I’ll dig some up',
    acceptReply: ['“Take a shovel to the forest floor. The dark stuff hides just under the surface.”'],
    declineLabel: 'Not today',
    declineReply: ['“No hurry. The forest keeps its dark in the same place.”'],
    progressOpening: ['“Any dark soil yet? It looks like night that fell down and stayed.”'],
    turnInOpening: ['{{name}} rubs the soil between two fingers. “Perfect. Here — I dug this up a while ago and never found the right person for it.”'],
    turnInReply: ['{{name}} presses a small earthy keepsake into your hand.'],
  },
  {
    id: 'favor-pink-shavings',
    title: 'Pink Shavings',
    summary: 'Gather ribbonwood sticks for a woodchuck’s workbench.',
    tier: 'favor',
    giverSpecies: ['woodchuck', 'squirrel', 'cat'],
    minFriendship: 'curious',
    objectives: [{ kind: 'collect', resource: 'ribbonwood-sticks', quantity: 3 }],
    reward: { trinketFamily: 'handmade', trinketTag: 'craft', friendship: 6 },
    opening: [
      '“Ribbonwood,” {{name}} says, sniffing the air as if it were a smell. “The pinkish sticks. Three of them and my bench stops wobbling.”',
    ],
    acceptLabel: 'I’ll find them',
    acceptReply: ['“Forest floor and scrap flats both. They lie about looking important.”'],
    declineLabel: 'Another time',
    declineReply: ['“The wobble is patient. So am I, mostly.”'],
    progressOpening: ['“Three pinkish sticks. Then the bench and I have words.”'],
    turnInOpening: ['“Look at the grain on those.” {{name}} sets them in a neat row. “Take this in trade. I made it, so keep your expectations low and your gratitude high.”'],
    turnInReply: ['{{name}} hands over a small handmade thing.'],
  },
  {
    id: 'favor-just-one-scoop',
    title: 'Just One Scoop',
    summary: 'Open the top layer of soil with a shovel.',
    tier: 'favor',
    giverSpecies: ['raccoon', 'woodchuck', 'fox'],
    giverPersonalities: ['bold', 'curious'],
    minFriendship: 'curious',
    objectives: [{ kind: 'dig', layer: 1 }],
    reward: { trinketFamily: 'curious', trinketTag: 'metal', friendship: 7 },
    opening: [
      '“Everything good starts with one honest scoop of ground,” {{name}} says, tapping the paper with a foot. “Make yourself a shovel and take one. Just one.”',
    ],
    acceptLabel: 'I’ll dig in',
    acceptReply: ['“The flimsy one will do. It only has to be brave for a moment.”'],
    declineLabel: 'Maybe later',
    declineReply: ['“The ground is not going anywhere. Rude of it, honestly.”'],
    progressOpening: ['“Have you opened the top layer yet? It makes a very satisfying sound.”'],
    turnInOpening: ['“There. You did a real thing to the real world.” {{name}} looks genuinely proud. “Here, for the first hole.”'],
    turnInReply: ['{{name}} gives you a curious little find.'],
  },
  {
    id: 'favor-berry-beginnings',
    title: 'Berry Beginnings',
    summary: 'Plant a raspberry bush from a seed packet.',
    tier: 'favor',
    giverSpecies: ['bunny', 'butterfly', 'bird'],
    giverPersonalities: ['gentle', 'curious'],
    minFriendship: 'curious',
    objectives: [{ kind: 'plant', seedId: 'raspberry-bush-seeds' }],
    reward: { trinketFamily: 'natural', trinketTag: 'plant', friendship: 7 },
    opening: [
      '“Raspberries are mostly patience with a little joy on top,” {{name}} says. “Sow one bush. I want to watch it decide to be a bush.”',
    ],
    acceptLabel: 'I’ll plant one',
    acceptReply: ['“Dig a bed first, then tuck it in. The packet turns up in the clearing and the meadow.”'],
    declineLabel: 'Not right now',
    declineReply: ['“Seeds wait better than anyone. It is their whole talent.”'],
    progressOpening: ['“Is the raspberry bush in the ground yet? I keep checking on it from here.”'],
    turnInOpening: ['“You planted it!” {{name}} does a small hop. “In a while there will be berries and I will be insufferable about them. Take this now, before I am.”'],
    turnInReply: ['{{name}} hands over a small green keepsake.'],
  },
  {
    id: 'favor-a-neat-pine',
    title: 'A Neat Little Pine',
    summary: 'Trim a pine tree and tidy its shaggy branches.',
    tier: 'favor',
    giverSpecies: ['bird', 'squirrel', 'woodchuck'],
    minFriendship: 'curious',
    objectives: [{ kind: 'trim', species: 'pine' }],
    reward: { trinketFamily: 'natural', trinketTag: 'material:wood', friendship: 7 },
    opening: [
      '“That pine by the path is getting positively shaggy,” {{name}} says. “A little trim would do it a world of good. Trees enjoy a haircut as much as anyone.”',
    ],
    acceptLabel: 'I’ll tidy it',
    acceptReply: ['“Kid’s scissors are plenty. A pine is a forgiving thing to practise on.”'],
    declineLabel: 'Not now',
    declineReply: ['“It will keep being shaggy. That is what pines do best.”'],
    progressOpening: ['“Did you get to the pine? I have been imagining it tidier.”'],
    turnInOpening: ['“Much better.” {{name}} studies the tree with an expert squint. “You have a good eye for a haircut. Here, for your trouble.”'],
    turnInReply: ['{{name}} gives you a tidy little keepsake.'],
  },
  {
    id: 'favor-under-the-green',
    title: 'Under the Green',
    summary: 'Walk into the forest and stand a while under the trees.',
    tier: 'favor',
    giverSpecies: ['butterfly', 'fox', 'bunny', 'cat'],
    minFriendship: 'curious',
    objectives: [{ kind: 'visitBiome', biome: 'forest' }],
    reward: { trinketFamily: 'seasonal', trinketTag: 'biome:forest', friendship: 6 },
    opening: [
      '“Some people have never stood under a proper canopy,” {{name}} says. “Go into the forest. Just once. Stand still and let it be tall at you.”',
    ],
    acceptLabel: 'I’ll go stand there',
    acceptReply: ['“Follow the paper until the light goes green. You will not miss it.”'],
    declineLabel: 'Later',
    declineReply: ['“The forest is very good at waiting. It has practice.”'],
    progressOpening: ['“Been under the trees yet? The quiet there is a different quiet.”'],
    turnInOpening: ['“You went.” {{name}} nods slowly. “Good. Green does something to a person. Here is a small thing for going.”'],
    turnInReply: ['{{name}} hands over a leaf-warm token.'],
  },
  {
    id: 'favor-a-root-worth-it',
    title: 'A Root Worth Digging',
    summary: 'Harvest a couple of crinkle carrots from your garden.',
    tier: 'favor',
    giverSpecies: ['bunny', 'woodchuck', 'bird', 'fox'],
    minFriendship: 'curious',
    objectives: [{ kind: 'harvest', resource: 'crinkle-carrots', quantity: 2 }],
    reward: { trinketFamily: 'natural', trinketTag: 'plant', friendship: 7 },
    opening: [
      '“Carrots are the best argument for digging that anyone ever made,” {{name}} says. “Grow a row and bring me two. Frilly tops, hidden prizes underneath.”',
    ],
    acceptLabel: 'I’ll bring carrots',
    acceptReply: ['“Sow crinkle-carrot seeds, wait them out, then pull. The packet is in the clearing and the meadow.”'],
    declineLabel: 'Another time',
    declineReply: ['“Carrots keep. In the ground, especially.”'],
    progressOpening: ['“Any carrots come up? I can practically taste the tops.”'],
    turnInOpening: ['“Oh, look at the crinkle on those.” {{name}} is delighted by a vegetable. “You are a gardener now. Take this, gardener.”'],
    turnInReply: ['{{name}} gives you something in honour of the harvest.'],
  },
  {
    id: 'favor-this-way-is-friendly',
    title: 'This Way Is Friendly',
    summary: 'Lay down a path plank so the way reads as walked.',
    tier: 'favor',
    giverSpecies: ['raccoon', 'cat', 'bunny'],
    giverPersonalities: ['bold', 'mischievous'],
    minFriendship: 'curious',
    objectives: [{ kind: 'place', templateKey: 'path-plank' }],
    reward: { trinketFamily: 'handmade', trinketTag: 'craft', friendship: 6 },
    opening: [
      '“A path is just a rumour that someone already walked here,” {{name}} says. “Put down one plank. Two if you are feeling generous. Then the next person knows the way.”',
    ],
    acceptLabel: 'I’ll lay one down',
    acceptReply: ['“Anywhere it makes sense to walk. A hammer helps. Confidence helps more.”'],
    declineLabel: 'Not just now',
    declineReply: ['“The grass will keep pretending to be a path. Poorly.”'],
    progressOpening: ['“Any planks down yet? The world could use one obvious hint.”'],
    turnInOpening: ['“I took the path. It was very legible.” {{name}} looks pleased with the world. “Here. A little something from a grateful traveller.”'],
    turnInReply: ['{{name}} presses a small keepsake into your hand.'],
  },

  // --- Errand: two steps, a friendly nudge ----------------------------------
  {
    id: 'errand-cardboard-stack',
    title: 'A Stack of Card',
    summary: 'Bring sunbaked cardboard back from the dry places.',
    tier: 'errand',
    giverSpecies: ['woodchuck', 'raccoon'],
    giverPersonalities: ['curious', 'bold'],
    minFriendship: 'friend',
    objectives: [{ kind: 'collect', resource: 'sunbaked-cardboard', quantity: 3 }],
    reward: { trinketFamily: 'handmade', trinketTag: 'craft', friendship: 8 },
    opening: [
      '“You have been out in the dry country,” {{name}} observes. “Good. Cardboard sunbakes out there into something worth building with. Three sheets and I will show you.”',
    ],
    acceptLabel: 'I’ll bring it back',
    acceptReply: ['“Dunes and flats. Bring a good grip — it is heavier than it looks.”'],
    declineLabel: 'Later',
    declineReply: ['“Card keeps. Mostly.”'],
    progressOpening: ['“Three sheets of sunbaked card. Then we build.”'],
    turnInOpening: ['“Excellent stock.” {{name}} sets it aside with real care. “Here is something from my own shelf.”'],
    turnInReply: ['{{name}} gives you a well-made keepsake.'],
  },
  {
    id: 'errand-first-bench',
    title: 'Somewhere to Sit',
    summary: 'Place a paper bench out in the world.',
    tier: 'errand',
    giverSpecies: ['woodchuck', 'raccoon', 'cat', 'fox'],
    minFriendship: 'friend',
    objectives: [{ kind: 'place', templateKey: 'paper-bench' }],
    reward: { trinketFamily: 'handmade', trinketTag: 'craft', friendship: 9 },
    opening: [
      '“A world with no benches is a world that expects you to keep moving,” {{name}} says darkly. “Build one. Put it anywhere. Prove them wrong.”',
    ],
    acceptLabel: 'I’ll build a bench',
    acceptReply: ['“It wants a hammer and a few materials. Anywhere with a view will do.”'],
    declineLabel: 'Can’t right now',
    declineReply: ['“The world will keep expecting things of you. So be it.”'],
    progressOpening: ['“Bench? Out there? Somewhere?”'],
    turnInOpening: ['“I saw it. I sat on it. It was extremely good.” {{name}} hands you a reward with a flourish.'],
    turnInReply: ['{{name}} gives you a trinket to commemorate the bench.'],
  },
  {
    id: 'errand-clay-and-cardstone',
    title: 'Clay and Cardstone',
    summary: 'Bring ochre clay and graphite cardstone to a builder.',
    tier: 'errand',
    giverSpecies: ['woodchuck', 'raccoon', 'meerkat'],
    minFriendship: 'friend',
    objectives: [
      { kind: 'collect', resource: 'ochre-paperclay', quantity: 2 },
      { kind: 'collect', resource: 'graphite-cardstone', quantity: 1 },
    ],
    reward: { trinketFamily: 'found', trinketTag: 'metal', friendship: 9 },
    opening: [
      '{{name}} has laid out two empty dishes, which is either very organised or very pointed. “Clay for the shape. Cardstone for the spine. Bring me some of each and I will show you a proper join.”',
    ],
    acceptLabel: 'Clay and cardstone, got it',
    acceptReply: ['“Clay comes up anywhere you dig. Cardstone hides deeper, or lies loose in the forest and the scrap.”'],
    declineLabel: 'Later',
    declineReply: ['“The dishes will sit empty. They are used to it.”'],
    progressOpening: ['“Two dishes, remember. Clay here, cardstone there.”'],
    turnInOpening: ['“Good stock. Now watch what two ordinary sorts of rock become in the right hands.” {{name}} hands you the result with due ceremony.'],
    turnInReply: ['{{name}} gives you something well-made in return.'],
  },
  {
    id: 'errand-cabbage-twice-over',
    title: 'Cabbage, Twice Over',
    summary: 'Sow folded-cabbage and bring back two heads.',
    tier: 'errand',
    giverSpecies: ['bunny', 'woodchuck', 'bird'],
    minFriendship: 'friend',
    objectives: [
      { kind: 'plant', seedId: 'folded-cabbage-seeds' },
      { kind: 'harvest', resource: 'folded-cabbage', quantity: 2 },
    ],
    reward: { trinketFamily: 'natural', trinketTag: 'plant', friendship: 9 },
    opening: [
      '“Cabbage is the most patient vegetable,” {{name}} says. “You put it in the ground, you forget about it, and months later it is enormous and slightly smug. Sow some. Bring me two heads.”',
    ],
    acceptLabel: 'I’ll grow cabbage',
    acceptReply: ['“Seed packets turn up in the clearing and the forest. Dig the bed, tuck them in, and let them get on with it.”'],
    declineLabel: 'Not today',
    declineReply: ['“Cabbage does not need you today. It never has, really.”'],
    progressOpening: ['“How is the cabbage? Enormous yet? Smug yet?”'],
    turnInOpening: ['“Look at the folds on these.” {{name}} weighs a head in each paw, satisfied. “You grew a whole vegetable. Here is a reward with some weight to it.”'],
    turnInReply: ['{{name}} gives you a solid little keepsake.'],
  },
  {
    id: 'errand-the-layer-underneath',
    title: 'The Layer Underneath',
    summary: 'Learn to reach the compact layer, then dig down to it.',
    tier: 'errand',
    giverSpecies: ['woodchuck', 'raccoon', 'fox', 'meerkat'],
    giverPersonalities: ['curious', 'bold'],
    minFriendship: 'friend',
    objectives: [
      { kind: 'learnTech', nodeId: 'digging-2' },
      { kind: 'dig', layer: 2 },
    ],
    reward: { trinketFamily: 'curious', trinketTag: 'metal', friendship: 10 },
    opening: [
      '“The surface is just the lid,” {{name}} says. “Under it there is a compact layer, pressed flat and full of better things. Learn the trick of reaching it, then go down a second time.”',
    ],
    acceptLabel: 'I’ll dig deeper',
    acceptReply: ['“The Professor keeps the plan. Learn it, make the next shovel up, and there you are.”'],
    declineLabel: 'Another day',
    declineReply: ['“It has been under there a long while. It is not impatient.”'],
    progressOpening: ['“Have you been past the first layer yet? That is where it gets interesting.”'],
    turnInOpening: ['“You went down.” {{name}} actually looks impressed. “The compact layer keeps its treasures close. So do I — here.”'],
    turnInReply: ['{{name}} hands over a curious keepsake.'],
  },
  {
    id: 'errand-twig-and-bench',
    title: 'Twigs into a Bench',
    summary: 'Gather kraft twigs, then set a paper bench down in the world.',
    tier: 'errand',
    giverSpecies: ['woodchuck', 'raccoon', 'cat'],
    giverPersonalities: ['curious', 'dramatic'],
    minFriendship: 'friend',
    exclusivityGroup: 'somewhere-to-sit',
    objectives: [
      { kind: 'collect', resource: 'kraft-twigs', quantity: 3 },
      { kind: 'place', templateKey: 'paper-bench' },
    ],
    reward: { trinketFamily: 'handmade', trinketTag: 'craft', friendship: 9 },
    opening: [
      '“Twigs are just benches that have not been told what to do yet,” {{name}} says. “Bring me three good ones — no, better: bring me the bench. Gather the twigs, then build it and set it down somewhere.”',
    ],
    acceptLabel: 'I’ll bring it, then build it',
    acceptReply: ['“Twigs lie loose in the clearing, the forest, and the meadow. After that, a hammer and a bit of nerve.”'],
    declineLabel: 'Can’t right now',
    declineReply: ['“The twigs will keep being twigs. That is the one thing they are reliable about.”'],
    progressOpening: ['“Twigs gathered? Bench placed? Either is a step.”'],
    turnInOpening: ['“I found it. I sat on it. It held.” {{name}} sounds faintly amazed. “Here, since you clearly build real things now.”'],
    turnInReply: ['{{name}} gives you a well-made reward.'],
  },
  {
    id: 'errand-fiber-and-sand',
    title: 'Fiber from the Sand',
    summary: 'Collect palm fiber and stand out in the dunes.',
    tier: 'errand',
    giverSpecies: ['meerkat', 'fox', 'bird'],
    minFriendship: 'friend',
    biomes: ['dunes'],
    objectives: [
      { kind: 'collect', resource: 'palm-fiber', quantity: 2 },
      { kind: 'visitBiome', biome: 'dunes' },
    ],
    reward: { trinketFamily: 'seasonal', trinketTag: 'biome:dunes', friendship: 9 },
    opening: [
      '“Out in the sand there are palms that will hand you a soft gray fiber if you ask politely,” {{name}} says. “Bring me a little, and see the dunes while you are there.”',
    ],
    acceptLabel: 'I’ll go out to the sand',
    acceptReply: ['“Scissors take the fiber off a palm. Mind the sun, and mind the sentries — they mean well.”'],
    declineLabel: 'Too far, for now',
    declineReply: ['“The sand is a long walk. It understands about long walks.”'],
    progressOpening: ['“Any palm fiber yet? Have you stood out on the sand?”'],
    turnInOpening: ['“Soft as anything.” {{name}} turns the fiber over. “And you took the walk. Here — something from out where the paper runs out.”'],
    turnInReply: ['{{name}} gives you a sun-warm keepsake.'],
  },

  // --- Odyssey: multi-step, high friendship, carries something --------------
  {
    id: 'odyssey-learn-something',
    title: 'Meet the Professor',
    summary: 'Learn a new plan at the knowledge tree.',
    tier: 'odyssey',
    giverSpecies: ['squirrel', 'raccoon', 'fox', 'cat', 'meerkat'],
    minFriendship: 'buddy',
    objectives: [{ kind: 'place', templateKey: 'paper-lamp' }],
    reward: { trinketFamily: 'curious', friendship: 15 },
    opening: [
      '“You cannot keep making the same four things forever,” {{name}} says, not unkindly. “Go and learn something. Then come back and show me a paper lamp, so I know it took.”',
    ],
    acceptLabel: 'I’ll learn something new',
    acceptReply: ['“The Professor will set you up. Patience or doing — either works. Bring back a lamp.”'],
    declineLabel: 'Not yet',
    declineReply: ['“Learning keeps too. But it keeps better if you use it.”'],
    progressOpening: ['“A paper lamp, once you have learned how. I will be right here.”'],
    turnInOpening: ['“A lamp! You learned a whole thing.” {{name}} turns it over, delighted. “Here. For the shelf of someone who is becoming someone.”'],
    turnInReply: ['{{name}} gives you a curious trinket in celebration.'],
  },
  {
    id: 'odyssey-message-to-chisel',
    title: 'Message for the Mill',
    summary: 'Carry word from a neighbor to the woodchuck at the mill.',
    tier: 'odyssey',
    giverSpecies: ['raccoon', 'fox', 'cat', 'meerkat', 'bird'],
    minFriendship: 'pet',
    objectives: [{ kind: 'talk', critterId: '-2,0#woodchuck' }],
    reward: { trinketFamily: 'story', friendship: 16 },
    opening: [
      '{{name}} looks around, then lowers their voice. “The woodchuck at the mill — tell them the offcut was worth it. They will know exactly what I mean. That is all. Just that.”',
    ],
    acceptLabel: 'I’ll tell them',
    acceptReply: ['“Thank you. The mill is one page over; the big saw gives it away.”'],
    declineLabel: 'Not right now',
    declineReply: ['“It has waited a while already. It can wait a little more.”'],
    progressOpening: ['“Have you been to the mill yet? The woodchuck is hard to miss.”'],
    turnInOpening: ['“You told them.” {{name}} exhales. “Good. Here — this is the kind of thing you give to someone who carries messages properly.”'],
    turnInReply: ['{{name}} hands over a trinket with real weight to it.'],
  },
  {
    id: 'odyssey-curls-and-lumber',
    title: 'Curls and Lumber',
    summary: 'Make heavier shears, cut bark curls from a redwood, and bind it all into lumber.',
    tier: 'odyssey',
    giverSpecies: ['woodchuck', 'raccoon', 'fox'],
    minFriendship: 'buddy',
    objectives: [
      { kind: 'craftTool', family: 'scissors', tier: 2 },
      { kind: 'collect', resource: 'redwood-bark-curls', quantity: 2 },
      { kind: 'craft', recipeId: 'bound-lumber' },
    ],
    reward: { trinketFamily: 'handmade', trinketTag: 'craft', friendship: 14 },
    opening: [
      '“Lumber is a promise you make to twigs,” {{name}} says. “But first you need curls, and a redwood laughs off kid’s scissors. Make the heavier shears. Cut the curls. Bind it into something flat and square.”',
      '“There is no shortcut to good lumber. That is rather the point of it.”',
    ],
    acceptLabel: 'Curls, then lumber',
    acceptReply: ['“Sturdy shears come from the tree of knowledge — make the kids’ pair first, then the heavier ones. The rest is just work.”'],
    declineLabel: 'Not the whole job',
    declineReply: ['“Good lumber is not a someday thing. Fair enough.”'],
    progressOpening: ['“Heavy shears? Curls? Lumber? Where has it got to?”'],
    turnInOpening: ['“A square, flat, honest length of lumber.” {{name}} holds it to the light. “You have gone from a person who gathers to a person who makes. Here — for the shelf of a maker.”'],
    turnInReply: ['{{name}} hands you something clearly meant for a maker.'],
  },
  {
    id: 'odyssey-word-across-the-paper',
    title: 'Word Across the Paper',
    summary: 'Carry a greeting to Chisel at the mill and Pip at the seed store.',
    tier: 'odyssey',
    giverSpecies: ['squirrel', 'raccoon', 'bird', 'meerkat'],
    minFriendship: 'pet',
    objectives: [
      { kind: 'visitPage', pageId: '-2,0' },
      { kind: 'talk', critterId: '-2,0#woodchuck' },
      { kind: 'talk', critterId: '1,0#pip' },
    ],
    reward: { trinketFamily: 'story', friendship: 16 },
    opening: [
      '{{name}} has been quiet for a while, which for them is almost a speech. “Two friends of mine are far apart and never hear from each other. Would you carry a greeting to both? Just that we are still thinking of them.”',
      '“It is not a big thing. It is just the kind of thing that keeps the world stitched.”',
    ],
    acceptLabel: 'I’ll carry your wishes',
    acceptReply: ['“Chisel keeps the mill, two pages over. Pip keeps the seed store, the other way. Tell them both hello from me.”'],
    declineLabel: 'Too much walking',
    declineReply: ['“Two pages is a lot. I understand; it has kept this long.”'],
    progressOpening: ['“Have you reached either of them yet? The mill, or the seed store?”'],
    turnInOpening: ['“You saw them both.” {{name}} is quiet a moment, then not. “They remember me. Good. Here — this is for someone who carries words kindly.”'],
    turnInReply: ['{{name}} gives you a trinket that plainly matters to them.'],
  },
  {
    id: 'odyssey-sow-the-sand',
    title: 'Something Growing in the Sand',
    summary: 'Reach the dunes, cut a little palm, and grow a tomato where nothing grows.',
    tier: 'odyssey',
    giverSpecies: ['meerkat', 'fox', 'raccoon'],
    minFriendship: 'buddy',
    biomes: ['dunes'],
    objectives: [
      { kind: 'visitBiome', biome: 'dunes' },
      { kind: 'trim', species: 'palm' },
      { kind: 'plant', seedId: 'paper-tomato-seeds' },
    ],
    reward: { trinketFamily: 'seasonal', trinketTag: 'biome:dunes', friendship: 15 },
    opening: [
      '“Everyone says nothing grows out here,” {{name}} says, with a glance at the horizon. “I would very much like you to be rude about that. Take a clipping off a palm, then grow a tomato in the sand and prove them tedious.”',
    ],
    acceptLabel: 'I’ll grow one in the sand',
    acceptReply: ['“Palms are out in the dunes; nothing else woody grows there. Tomato packets turn up in the meadow and the sand both.”'],
    declineLabel: 'The sand wins this time',
    declineReply: ['“The sand usually does. But not always.”'],
    progressOpening: ['“Palm clipped? Tomato planted? Even one of those is a good day.”'],
    turnInOpening: ['“You put something green in the sand.” {{name}} does not look at the horizon at all. “That is a real thing. Take this — it has been waiting for someone who would.”'],
    turnInReply: ['{{name}} hands you a sun-worn keepsake.'],
  },
  {
    id: 'odyssey-the-travelling-plant',
    title: 'A Plant for the Mill',
    summary: 'Lift a growing buttonbloom and carry it to Chisel at the mill.',
    tier: 'odyssey',
    giverSpecies: ['bunny', 'squirrel', 'raccoon', 'butterfly'],
    giverPersonalities: ['gentle', 'curious'],
    minFriendship: 'buddy',
    objectives: [
      { kind: 'deliver', itemId: 'plant:buttonbloom-seeds' },
      { kind: 'talk', critterId: '-2,0#woodchuck' },
    ],
    reward: { trinketFamily: 'story', trinketTag: 'plant', friendship: 14 },
    opening: [
      '“Chisel spends all day at the mill and never sees anything green,” {{name}} says. “Grow a Buttonbloom, lift it carefully, and carry it over. A living plant is a better gift than a finished one.”',
    ],
    acceptLabel: 'I’ll grow one and bring it',
    acceptReply: ['“Plant a Buttonbloom and let it root, then lift it with your hoe. It will travel fine. Chisel is two pages over, at the big saw.”'],
    declineLabel: 'Not this time',
    declineReply: ['“It is the sort of errand that should be chosen, not asked twice.”'],
    progressOpening: ['“Is there a little plant in your pockets yet? Chisel has no idea it is coming.”'],
    turnInOpening: ['“You carried a whole living thing across the paper.” {{name}} is quietly delighted. “Chisel will not stop talking about it. Here — for the plant-bearer.”'],
    turnInReply: ['{{name}} gives you a keepsake that smells faintly of soil.'],
  },

  // --- The tropical batch (2026-09-18), with the biome's own materials,
  // species, and keepsakes. Nothing here is out of reach: the tropics are a
  // walk, the shovel is the starter one, and the scissors are whatever pair
  // you already own. ---
  {
    id: 'favor-jungle-loam',
    title: 'The Good Damp Dirt',
    summary: 'Bring back a scoop of the jungle’s wet ground for a wallow.',
    tier: 'favor',
    giverSpecies: ['raccoon', 'parrot', 'bunny'],
    minFriendship: 'curious',
    objectives: [{ kind: 'collect', resource: 'jungle-loam', quantity: 2 }],
    reward: { trinketFamily: 'natural', trinketTag: 'biome:tropical', friendship: 6 },
    opening: [
      '“The meadow dirt is fine, if you like dirt that gives up,” {{name}} says. “But the jungle floor? Dark, green, always a little damp. Two scoops and my wallow becomes a destination.”',
    ],
    acceptLabel: 'I’ll fetch some',
    acceptReply: ['“Follow the wet air. When the ground starts keeping your footprints as souvenirs, you are there.”'],
    declineLabel: 'Another time',
    declineReply: ['“The wallow has waited this long. It is very patient mud.”'],
    progressOpening: ['“Any of the good damp dirt yet? Your boots look disappointingly dry.”'],
    turnInOpening: ['“Oh, that is the good stuff.” {{name}} presses a paw into it and sighs. “Here — I traded for this with a parrot, which is why it is loud and green.”'],
    turnInReply: ['{{name}} hands over something bright from the jungle.'],
  },
  {
    id: 'favor-palm-preen',
    title: 'Feather-Oil Fronds',
    summary: 'Bring palm clippings for a parrot preening between arguments.',
    tier: 'favor',
    giverSpecies: ['parrot', 'bird'],
    minFriendship: 'curious',
    objectives: [{ kind: 'collect', resource: 'palm-clippings', quantity: 3 }],
    reward: { trinketFamily: 'natural', trinketTag: 'feather', friendship: 6 },
    opening: [
      '“Do not tell the flock,” {{name}} says, preening badly, “but I have argued with so many hibiscus bushes this week that my feathers need help. Three palm fronds. The good green ones.”',
    ],
    acceptLabel: 'I’ll clip some',
    acceptReply: ['“Scissors and any palm. The dunes have a few; the jungle has all of them. I would go myself but I am mid-argument.”'],
    declineLabel: 'Sort it out with the hibiscus',
    declineReply: ['“Fair. It started it.”'],
    progressOpening: ['“Fronds yet? The flock is noticing. That is the worst part.”'],
    turnInOpening: ['“Perfect. Green, flat, still slightly smug.” {{name}} disappears into them. A muffled voice continues: “Take this. I have spares. I have SO many spares.”'],
    turnInReply: ['{{name}} gifts you something bright that fell mid-preen.'],
  },
  {
    id: 'errand-wet-ground',
    title: 'Where the Green Gets Loud',
    summary: 'Walk to the tropics and feel what wet ground grows.',
    tier: 'errand',
    giverSpecies: ['squirrel', 'bird', 'raccoon', 'cat'],
    minFriendship: 'friend',
    objectives: [
      { kind: 'visitBiome', biome: 'tropical' },
      { kind: 'collect', resource: 'palm-fiber', quantity: 2 },
    ],
    reward: { trinketFamily: 'handmade', trinketTag: 'biome:tropical', friendship: 8 },
    opening: [
      '“You keep gathering the same six things from the same three pages,” {{name}} says, not unkindly. “Somewhere out there the paper turns dark green and everything grows loudly. Go stand in it. Bring me back something soft from under a palm while you are there.”',
    ],
    acceptLabel: 'I’ll go and see',
    acceptReply: ['“Follow the humidity. When your boots stop drying, keep going.”'],
    declineLabel: 'Too far for now',
    declineReply: ['“The jungle will still be loud tomorrow. It does not know how to be otherwise.”'],
    progressOpening: ['“Stood in the loud green yet? Soft fiber, from under a palm.”'],
    turnInOpening: ['“You went!” {{name}} takes the fiber and the story at the same time. “Here — this came back with a trader who took the same walk.”'],
    turnInReply: ['{{name}} hands over a keepsake that still feels warm.'],
  },
  {
    id: 'errand-banana-trim',
    title: 'One Banana Tree',
    summary: 'Trim a banana tree in the jungle — gently, the plan says.',
    tier: 'errand',
    giverSpecies: ['parrot', 'bird', 'bunny'],
    minFriendship: 'friend',
    objectives: [
      { kind: 'visitBiome', biome: 'tropical' },
      { kind: 'trim', species: 'banana' },
    ],
    reward: { trinketFamily: 'natural', trinketTag: 'plant', friendship: 8 },
    opening: [
      '“Everyone trims the pines and nobody touches the bananas,” {{name}} complains. “They grow like an apology that got out of hand. Take your scissors to one. It is basically a haircut. They love it. Probably.”',
    ],
    acceptLabel: 'I’ll give one a trim',
    acceptReply: ['“Jungle, banana, snip. It drops clippings like confetti, which frankly it can spare.”'],
    declineLabel: 'Maybe later',
    declineReply: ['“The bananas continue their candidacy for biggest leaf. Fine. FINE.”'],
    progressOpening: ['“Snip a banana yet? They are the tree having the most fun out there.”'],
    turnInOpening: ['“You did it, and it forgave you instantly. That is the banana way.” {{name}} produces a small thing. “For service to oversized foliage.”'],
    turnInReply: ['{{name}} hands over a leafy little trophy.'],
  },
  {
    id: 'favor-rainfold-shine',
    title: 'A Particular Shine',
    summary: 'Dig up rainfold pebbles — the wet stone with the fold in it.',
    tier: 'favor',
    giverSpecies: ['raccoon', 'parrot'],
    minFriendship: 'curious',
    objectives: [{ kind: 'dig', layer: 2 }],
    reward: { trinketFamily: 'natural', trinketTag: 'material:stone', friendship: 6 },
    opening: [
      '“There is a stone in the jungle ground,” {{name}} says, “folded like a letter somebody cried on. Aqua, cool, a crease right across. The raccoons trade for them. Go down a layer or two and see what the wet dirt is hiding.”',
    ],
    acceptLabel: 'I’ll dig around',
    acceptReply: ['“Deeper than the first scoop. The good layer is the second one. That is where the ground keeps its correspondence.”'],
    declineLabel: 'Not today',
    declineReply: ['“The stones are excellent at waiting underground. It is their whole arrangement.”'],
    progressOpening: ['“Found the folded ones yet? Second layer down, in the wet.”'],
    turnInOpening: ['“There — see the crease? Rain did that.” {{name}} holds one up to the light, then hands you something else entirely. “Fair trade. It always is.”'],
    turnInReply: ['{{name}} presses a small stony keepsake into your hand.'],
  },
  {
    id: 'odyssey-jungle-post',
    title: 'Word for the Jungle',
    summary: 'Carry a message all the way to a parrot in the tropics.',
    tier: 'odyssey',
    giverSpecies: ['raccoon', 'fox', 'cat', 'meerkat', 'bird'],
    minFriendship: 'buddy',
    objectives: [
      { kind: 'visitBiome', biome: 'tropical' },
      { kind: 'talk', critterId: 'parrot' },
    ],
    reward: { trinketFamily: 'story', trinketTag: 'biome:tropical', friendship: 15 },
    opening: [
      '{{name}} looks around, then lowers their voice. “There is a parrot in the jungle — any parrot will insist it is the one — who repeats everything. Tell them the meadow says hello, and that we noticed the rain. They will know what it means. Or they will make something up, which is better.”',
    ],
    acceptLabel: 'I’ll carry it',
    acceptReply: ['“It is a long walk and a short message. That is what makes it worth carrying.”'],
    declineLabel: 'Not right now',
    declineReply: ['“The jungle is not going anywhere. Neither, apparently, is the message.”'],
    progressOpening: ['“Have you found the tropics yet? Listen for the loudest green.”'],
    turnInOpening: ['“You told a parrot a secret,” {{name}} says, awed. “It is a jungle-wide secret now. Here — carried things should be carried home.”'],
    turnInReply: ['{{name}} hands over a trinket with real distance in it.'],
  },
  // --- The canopy crowd (2026-09-18): toucan, sloth, monkey. ---------------
  {
    id: 'favor-crepe-vine',
    title: 'Something Stretchy',
    summary: 'Trim crepe-paper vine from the hanging vines on the tall jungle trees.',
    tier: 'favor',
    giverSpecies: ['monkey', 'toucan', 'parrot'],
    minFriendship: 'curious',
    objectives: [{ kind: 'collect', resource: 'crepe-vine', quantity: 3 }],
    reward: { trinketFamily: 'natural', trinketTag: 'plant', friendship: 7 },
    opening: [
      '“See the long vines hanging off the big trees?” {{name}} points, then points again, harder. “Snip the bottom of one. It comes off twisty and stretchy — crepe paper, the good kind. I need three. For… reasons. Excellent reasons.”',
    ],
    acceptLabel: 'I’ll trim some vine',
    acceptReply: ['“Scissors, vine, snip. It grows back. Everything out here grows back, it is very forgiving.”'],
    declineLabel: 'Not right now',
    declineReply: ['“The vines will keep hanging. It is their whole job.”'],
    progressOpening: ['“Any crepe vine yet? Tall trees, long vines, bottom end.”'],
    turnInOpening: ['“Oh, that is SO stretchy.” {{name}} tests a piece, delighted. “Here — a fair trade for something this bouncy.”'],
    turnInReply: ['{{name}} hands over a leafy little keepsake.'],
  },
  {
    id: 'errand-say-hi-sloth',
    title: 'Hello, Very Slowly',
    summary: 'Find a sloth in the jungle canopy and say hello. Allow time for a reply.',
    tier: 'errand',
    giverSpecies: ['monkey', 'toucan', 'parrot', 'bird'],
    minFriendship: 'curious',
    objectives: [
      { kind: 'visitBiome', biome: 'tropical' },
      { kind: 'talk', critterId: 'sloth' },
    ],
    reward: { trinketFamily: 'story', trinketTag: 'biome:tropical', friendship: 9 },
    opening: [
      '“There is a sloth up in the big trees who has been trying to finish a sentence since Tuesday,” {{name}} says. “Go say hello. Stand right underneath — you can talk up into the branches. Then wait. Then wait a bit more.”',
    ],
    acceptLabel: 'I’ll go say hi',
    acceptReply: ['“Look for the branch that is smiling. That is the sloth.”'],
    declineLabel: 'Maybe later',
    declineReply: ['“No rush. Truly. The sloth would be the first to agree.”'],
    progressOpening: ['“Met the sloth yet? Look up. Further up. There.”'],
    turnInOpening: ['“You talked to a sloth and came back the same week!” {{name}} is impressed. “Here, for patience above and beyond.”'],
    turnInReply: ['{{name}} hands over a calm, slightly fuzzy keepsake.'],
  },
  {
    id: 'favor-sloth-hammock',
    title: 'A Vine for a Nap',
    summary: 'Trim a hanging vine so the sloth can see about a new hammock.',
    tier: 'favor',
    giverSpecies: ['sloth'],
    minFriendship: 'curious',
    objectives: [{ kind: 'trim', species: 'vine' }],
    reward: { trinketFamily: 'handmade', trinketTag: 'biome:tropical', friendship: 10 },
    opening: [
      '{{name}} blinks. Slowly. “I have been… thinking… about a hammock. A vine one. I would… trim one myself… but that sounds… like a lot. Could you…?”',
    ],
    acceptLabel: 'I’ll trim a vine for you',
    acceptReply: ['“Thank you… I will be… right here. Obviously.”'],
    declineLabel: 'Not today',
    declineReply: ['“That’s… fine. I’ll… think about it… some more. For a while.”'],
    progressOpening: ['“Any… vine? No rush. I mean it… more than anyone… has ever meant it.”'],
    turnInOpening: ['{{name}} regards the vine for a long, happy moment. “Perfect. I’ll… start weaving it… soon. Ish. Here… for you.”'],
    turnInReply: ['{{name}} very slowly hands over a small handmade thing.'],
  },
  {
    id: 'favor-blotting-caps',
    title: 'Soft as a Mushroom',
    summary: 'Snip blotting-paper caps from a mushroom cluster on the forest or jungle floor.',
    tier: 'favor',
    giverSpecies: ['monkey', 'sloth', 'squirrel', 'woodchuck'],
    minFriendship: 'curious',
    objectives: [{ kind: 'collect', resource: 'blotting-caps', quantity: 2 }],
    reward: { trinketFamily: 'natural', trinketTag: 'plant', friendship: 6 },
    opening: [
      '“The mushrooms on the floor,” {{name}} says, “are blotting paper. Soft, spongy, they drink up the damp. Snip a couple of caps for me? They grow right back — mushrooms are very good sports about it.”',
    ],
    acceptLabel: 'I’ll snip a couple',
    acceptReply: ['“Low down, in the shade. Scissors, not boots.”'],
    declineLabel: 'Not now',
    declineReply: ['“The mushrooms will not mind. They are extremely unbothered.”'],
    progressOpening: ['“Caps yet? The spongy ones, in the shade.”'],
    turnInOpening: ['“Oh, perfect — so squishy.” {{name}} gives them an approving poke. “Here, for the good find.”'],
    turnInReply: ['{{name}} hands over a small earthy keepsake.'],
  },
];
